
package views;

import controllers.KhachHangController;
import models.KhachHang;

/**
 *
 * @author duato
 */
public class KhachHangJDialog extends javax.swing.JDialog {

    /**
     * Creates new form HoTieuThuJFrame
     */
    public KhachHangJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        KhachHangController controller = new KhachHangController(this, btnSubmit, jtfMaKH, jtfHoTen, jtaDiaChi, jtfCCCD, jtfSoDienThoai, jdateNgaySinh, jlbMsg);
        controller.setEvent();
    }
    
    public KhachHangJDialog(java.awt.Frame parent, boolean modal, KhachHang khachHang) {
        super(parent, modal);
        initComponents();
        
        KhachHangController controller = new KhachHangController(this, btnSubmit, jtfMaKH, jtfHoTen, jtaDiaChi, jtfCCCD, jtfSoDienThoai, jdateNgaySinh, jlbMsg);
        controller.setView(khachHang);
        controller.setEvent();
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRoot = new javax.swing.JPanel();
        jpnInfo = new javax.swing.JPanel();
        jlbMaKH = new javax.swing.JLabel();
        jlbHoTen = new javax.swing.JLabel();
        jlbDiaChi = new javax.swing.JLabel();
        jlbCCCD = new javax.swing.JLabel();
        jlbNgaySinh = new javax.swing.JLabel();
        jlbSoDienThoai = new javax.swing.JLabel();
        jtfMaKH = new javax.swing.JTextField();
        jtfHoTen = new javax.swing.JTextField();
        jtfCCCD = new javax.swing.JTextField();
        jtfSoDienThoai = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDiaChi = new javax.swing.JTextArea();
        jdateNgaySinh = new com.toedter.calendar.JDateChooser();
        jlbMsg = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

        jpnRoot.setBackground(new java.awt.Color(255, 255, 255));

        jpnInfo.setBackground(new java.awt.Color(255, 255, 255));
        jpnInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin hộ tiêu thụ nước", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jlbMaKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbMaKH.setLabelFor(jtfMaKH);
        jlbMaKH.setText("Mã khách hàng:");

        jlbHoTen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbHoTen.setLabelFor(jtfHoTen);
        jlbHoTen.setText("Họ tên khách hàng:");

        jlbDiaChi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbDiaChi.setLabelFor(jtaDiaChi);
        jlbDiaChi.setText("Địa chỉ:");

        jlbCCCD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbCCCD.setLabelFor(jtfCCCD);
        jlbCCCD.setText("Số CMND/CCCD:");

        jlbNgaySinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbNgaySinh.setLabelFor(jdateNgaySinh);
        jlbNgaySinh.setText("Ngày sinh:");

        jlbSoDienThoai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbSoDienThoai.setLabelFor(jtfSoDienThoai);
        jlbSoDienThoai.setText("Số điện thoại:");

        jtfMaKH.setEditable(false);
        jtfMaKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jtfHoTen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jtfCCCD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jtfSoDienThoai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jtaDiaChi.setColumns(20);
        jtaDiaChi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtaDiaChi.setRows(5);
        jScrollPane1.setViewportView(jtaDiaChi);

        jdateNgaySinh.setDateFormatString("yyyy-MM-dd");
        jdateNgaySinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jpnInfoLayout = new javax.swing.GroupLayout(jpnInfo);
        jpnInfo.setLayout(jpnInfoLayout);
        jpnInfoLayout.setHorizontalGroup(
            jpnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnInfoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jpnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jlbHoTen)
                        .addComponent(jlbMaKH, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jlbDiaChi))
                .addGap(18, 18, 18)
                .addGroup(jpnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jtfMaKH, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfHoTen))
                .addGap(30, 30, 30)
                .addGroup(jpnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnInfoLayout.createSequentialGroup()
                        .addGroup(jpnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbCCCD)
                            .addComponent(jlbNgaySinh))
                        .addGap(18, 18, 18)
                        .addGroup(jpnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jdateNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfCCCD, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpnInfoLayout.createSequentialGroup()
                        .addComponent(jlbSoDienThoai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtfSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        jpnInfoLayout.setVerticalGroup(
            jpnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnInfoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jpnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbMaKH)
                    .addComponent(jlbCCCD)
                    .addComponent(jtfMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jpnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlbHoTen)
                        .addComponent(jlbNgaySinh)
                        .addComponent(jtfHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jdateNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jpnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlbSoDienThoai)
                        .addComponent(jtfSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbDiaChi))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jlbMsg.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbMsg.setForeground(new java.awt.Color(255, 51, 51));
        jlbMsg.setText("...");

        btnSubmit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_home.png"))); // NOI18N
        btnSubmit.setText("Lưu thông tin");

        javax.swing.GroupLayout jpnRootLayout = new javax.swing.GroupLayout(jpnRoot);
        jpnRoot.setLayout(jpnRootLayout);
        jpnRootLayout.setHorizontalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpnInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpnRootLayout.createSequentialGroup()
                        .addComponent(jlbMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSubmit)))
                .addContainerGap())
        );
        jpnRootLayout.setVerticalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmit))
                .addGap(18, 18, 18)
                .addComponent(jpnInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpnInfo.getAccessibleContext().setAccessibleName("Thông tin hộ tiêu thụ nước");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdateNgaySinh;
    private javax.swing.JLabel jlbCCCD;
    private javax.swing.JLabel jlbDiaChi;
    private javax.swing.JLabel jlbHoTen;
    private javax.swing.JLabel jlbMaKH;
    private javax.swing.JLabel jlbMsg;
    private javax.swing.JLabel jlbNgaySinh;
    private javax.swing.JLabel jlbSoDienThoai;
    private javax.swing.JPanel jpnInfo;
    private javax.swing.JPanel jpnRoot;
    private javax.swing.JTextArea jtaDiaChi;
    private javax.swing.JTextField jtfCCCD;
    private javax.swing.JTextField jtfHoTen;
    private javax.swing.JTextField jtfMaKH;
    private javax.swing.JTextField jtfSoDienThoai;
    // End of variables declaration//GEN-END:variables
}
