
package views;

import controllers.LoginController;

/**
 *
 * @author duato
 */
public class LoginJFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginJFrame
     */
    public LoginJFrame() {
        initComponents();
        //Icon
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/iconapp.png")));
        //Them coltroller
        LoginController controller = new LoginController(this, jbtnLogin, jtfUserName, jpfPassword, jlbLoginMessage);
        controller.setEvent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnLogo = new javax.swing.JPanel();
        jlbLogo = new javax.swing.JLabel();
        jpnLogin = new javax.swing.JPanel();
        jpnLoginTitle = new javax.swing.JPanel();
        jlbLoginTitle = new javax.swing.JLabel();
        jpnLoginInfo = new javax.swing.JPanel();
        jpnUserName = new javax.swing.JPanel();
        jlbUserName = new javax.swing.JLabel();
        jtfUserName = new javax.swing.JTextField();
        jpnPassword = new javax.swing.JPanel();
        jlbPassword = new javax.swing.JLabel();
        jpfPassword = new javax.swing.JPasswordField();
        jpnLoginBTN = new javax.swing.JPanel();
        jbtnLogin = new javax.swing.JButton();
        jlbLoginMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Đăng nhập");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jpnLogo.setBackground(new java.awt.Color(255, 255, 255));
        jpnLogo.setPreferredSize(new java.awt.Dimension(300, 0));

        jlbLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/evnBackgroundBill.png"))); // NOI18N

        javax.swing.GroupLayout jpnLogoLayout = new javax.swing.GroupLayout(jpnLogo);
        jpnLogo.setLayout(jpnLogoLayout);
        jpnLogoLayout.setHorizontalGroup(
            jpnLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, Short.MAX_VALUE)
        );
        jpnLogoLayout.setVerticalGroup(
            jpnLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnLogoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jlbLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(102, 102, 102))
        );

        getContentPane().add(jpnLogo, java.awt.BorderLayout.WEST);

        jpnLogin.setBackground(new java.awt.Color(255, 255, 255));
        jpnLogin.setPreferredSize(new java.awt.Dimension(400, 400));

        jpnLoginTitle.setBackground(new java.awt.Color(255, 255, 255));

        jlbLoginTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbLoginTitle.setForeground(new java.awt.Color(0, 51, 255));
        jlbLoginTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbLoginTitle.setText("NƯỚC SẠCH NAM TỪ LIÊM");
        jlbLoginTitle.setToolTipText("");

        javax.swing.GroupLayout jpnLoginTitleLayout = new javax.swing.GroupLayout(jpnLoginTitle);
        jpnLoginTitle.setLayout(jpnLoginTitleLayout);
        jpnLoginTitleLayout.setHorizontalGroup(
            jpnLoginTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnLoginTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbLoginTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnLoginTitleLayout.setVerticalGroup(
            jpnLoginTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnLoginTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbLoginTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpnLoginInfo.setBackground(new java.awt.Color(255, 255, 255));

        jpnUserName.setBackground(new java.awt.Color(255, 255, 255));

        jlbUserName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbUserName.setText("Tài khoản");
        jlbUserName.setPreferredSize(new java.awt.Dimension(300, 20));

        jtfUserName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfUserName.setPreferredSize(new java.awt.Dimension(300, 30));

        javax.swing.GroupLayout jpnUserNameLayout = new javax.swing.GroupLayout(jpnUserName);
        jpnUserName.setLayout(jpnUserNameLayout);
        jpnUserNameLayout.setHorizontalGroup(
            jpnUserNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnUserNameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnUserNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jpnUserNameLayout.setVerticalGroup(
            jpnUserNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnUserNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
        );

        jpnPassword.setBackground(new java.awt.Color(255, 255, 255));

        jlbPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbPassword.setText("Mật khẩu");
        jlbPassword.setPreferredSize(new java.awt.Dimension(300, 20));

        jpfPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jpfPassword.setPreferredSize(new java.awt.Dimension(300, 30));

        javax.swing.GroupLayout jpnPasswordLayout = new javax.swing.GroupLayout(jpnPassword);
        jpnPassword.setLayout(jpnPasswordLayout);
        jpnPasswordLayout.setHorizontalGroup(
            jpnPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlbPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpfPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );
        jpnPasswordLayout.setVerticalGroup(
            jpnPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpnLoginBTN.setBackground(new java.awt.Color(255, 255, 255));

        jbtnLogin.setBackground(new java.awt.Color(204, 204, 204));
        jbtnLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnLogin.setText("Đăng Nhập");
        jbtnLogin.setPreferredSize(new java.awt.Dimension(300, 25));

        javax.swing.GroupLayout jpnLoginBTNLayout = new javax.swing.GroupLayout(jpnLoginBTN);
        jpnLoginBTN.setLayout(jpnLoginBTNLayout);
        jpnLoginBTNLayout.setHorizontalGroup(
            jpnLoginBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnLoginBTNLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jpnLoginBTNLayout.setVerticalGroup(
            jpnLoginBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnLoginBTNLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
        );

        jlbLoginMessage.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jlbLoginMessage.setForeground(new java.awt.Color(255, 0, 0));
        jlbLoginMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbLoginMessage.setText("Vui lòng nhập thông tin đăng nhập!");

        javax.swing.GroupLayout jpnLoginInfoLayout = new javax.swing.GroupLayout(jpnLoginInfo);
        jpnLoginInfo.setLayout(jpnLoginInfoLayout);
        jpnLoginInfoLayout.setHorizontalGroup(
            jpnLoginInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnLoginInfoLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jpnLoginInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpnLoginBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnLoginInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jpnPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jpnUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnLoginInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbLoginMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jpnLoginInfoLayout.setVerticalGroup(
            jpnLoginInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnLoginInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpnUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jpnPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jpnLoginBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbLoginMessage)
                .addContainerGap())
        );

        javax.swing.GroupLayout jpnLoginLayout = new javax.swing.GroupLayout(jpnLogin);
        jpnLogin.setLayout(jpnLoginLayout);
        jpnLoginLayout.setHorizontalGroup(
            jpnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpnLoginInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnLoginTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpnLoginLayout.setVerticalGroup(
            jpnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnLoginTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnLoginInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jpnLogin, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnLogin;
    private javax.swing.JLabel jlbLoginMessage;
    private javax.swing.JLabel jlbLoginTitle;
    private javax.swing.JLabel jlbLogo;
    private javax.swing.JLabel jlbPassword;
    private javax.swing.JLabel jlbUserName;
    private javax.swing.JPasswordField jpfPassword;
    private javax.swing.JPanel jpnLogin;
    private javax.swing.JPanel jpnLoginBTN;
    private javax.swing.JPanel jpnLoginInfo;
    private javax.swing.JPanel jpnLoginTitle;
    private javax.swing.JPanel jpnLogo;
    private javax.swing.JPanel jpnPassword;
    private javax.swing.JPanel jpnUserName;
    private javax.swing.JTextField jtfUserName;
    // End of variables declaration//GEN-END:variables
}
