/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import beans.DanhMucBean;
import controllers.ChuyenManHinhController;
import controllers.MenuController;
import controllers.StatusBarController;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author duato
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        ChuyenManHinhController controller = new ChuyenManHinhController(jpnView);
        controller.setDashboard(jpnMenuTitle, jlbMenuTitle);
        //toan man hinh
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        //Icon Jframe
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/iconapp.png")));
        //Thêm leftMenu và phân quyền
        List<DanhMucBean> listItem = new ArrayList<>();
        
        listItem.add(new DanhMucBean("Home", jpnMenuTitle, jlbMenuTitle));
        listItem.add(new DanhMucBean("HoTieuThu", jpnMenu1, jlbMenu1));
        //Quyen cap nhap chi so nuoc
        if (main.Main.nhanVien.getChucVu().equalsIgnoreCase("QuanLy")||
            main.Main.nhanVien.getChucVu().equalsIgnoreCase("ThoNuoc")) {
            listItem.add(new DanhMucBean("ChiSoNuoc", jpnMenu2, jlbMenu2));
        } else {
            jlbMenu2.setEnabled(false);
            jlbMenu2.setEnabled(false);
        }
        //Quyen xem khach chua thanh toan va lap hoa don
        if (main.Main.nhanVien.getChucVu().equalsIgnoreCase("QuanLy") || 
            main.Main.nhanVien.getChucVu().equalsIgnoreCase("ThuTien")) {
            listItem.add(new DanhMucBean("ThanhToan", jpnMenu3, jlbMenu3));
            listItem.add(new DanhMucBean("HoaDon", jpnMenu4, jlbMenu4));
        } else {
            jlbMenu3.setEnabled(false);
            jlbMenu3.setEnabled(false);
            jlbMenu4.setEnabled(false);
            jlbMenu4.setEnabled(false);
        }
        //Quyen cua quan tri vien
        if (main.Main.nhanVien.getChucVu().equalsIgnoreCase("QuanLy")) {
            listItem.add(new DanhMucBean("ThongKe", jpnMenu5, jlbMenu5));
        } else {
            jlbMenu5.setEnabled(false);
            jlbMenu5.setEnabled(false);
        }
        
        
        controller.setEvent(listItem);
        
        
        // XỬ LÝ MENU BAR
        
        MenuController.setMenuBar(jMenuBar);
        // XỬ LÝ STATUS BAR
        StatusBarController statusBarController = new StatusBarController(jlbTime, jlbDate, jlbMessage);
        statusBarController.setStatusBarTimer();
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent event) {
                statusBarController.exitProcedure();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRoot = new javax.swing.JPanel();
        jpnMenu = new javax.swing.JPanel();
        jpnMenuTitle = new javax.swing.JPanel();
        jlbMenuTitle = new javax.swing.JLabel();
        jpnMenu1 = new javax.swing.JPanel();
        jlbMenu1 = new javax.swing.JLabel();
        jpnMenu2 = new javax.swing.JPanel();
        jlbMenu2 = new javax.swing.JLabel();
        jpnMenu3 = new javax.swing.JPanel();
        jlbMenu3 = new javax.swing.JLabel();
        jpnMenu4 = new javax.swing.JPanel();
        jlbMenu4 = new javax.swing.JLabel();
        jpnMenu5 = new javax.swing.JPanel();
        jlbMenu5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jpnView = new javax.swing.JPanel();
        jpnStatusBar = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jlbTime = new javax.swing.JLabel();
        jlbDate = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jlbMessage = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ TIỀN NƯỚC");

        jpnRoot.setBackground(new java.awt.Color(204, 204, 204));
        jpnRoot.setPreferredSize(new java.awt.Dimension(1381, 700));

        jpnMenu.setBackground(new java.awt.Color(82, 83, 81));

        jpnMenuTitle.setBackground(new java.awt.Color(226, 125, 96));

        jlbMenuTitle.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jlbMenuTitle.setForeground(new java.awt.Color(255, 255, 255));
        jlbMenuTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbMenuTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/electricity-bill.png"))); // NOI18N
        jlbMenuTitle.setText("QUẢN LÝ TIỀN NƯỚC");
        jlbMenuTitle.setToolTipText("");

        javax.swing.GroupLayout jpnMenuTitleLayout = new javax.swing.GroupLayout(jpnMenuTitle);
        jpnMenuTitle.setLayout(jpnMenuTitleLayout);
        jpnMenuTitleLayout.setHorizontalGroup(
            jpnMenuTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnMenuTitleLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbMenuTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        jpnMenuTitleLayout.setVerticalGroup(
            jpnMenuTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenuTitleLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbMenuTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jpnMenu1.setBackground(new java.awt.Color(0, 153, 153));

        jlbMenu1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jlbMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/quan_Li.png"))); // NOI18N
        jlbMenu1.setText("Quản Lý Hộ Tiêu Thụ");
        jlbMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jpnMenu1Layout = new javax.swing.GroupLayout(jpnMenu1);
        jpnMenu1.setLayout(jpnMenu1Layout);
        jpnMenu1Layout.setHorizontalGroup(
            jpnMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenu1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlbMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jpnMenu1Layout.setVerticalGroup(
            jpnMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenu1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlbMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jpnMenu2.setBackground(new java.awt.Color(0, 153, 153));

        jlbMenu2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbMenu2.setForeground(new java.awt.Color(255, 255, 255));
        jlbMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cap_nhat.png"))); // NOI18N
        jlbMenu2.setText("Cập Nhập Chỉ Số Nước");
        jlbMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jpnMenu2Layout = new javax.swing.GroupLayout(jpnMenu2);
        jpnMenu2.setLayout(jpnMenu2Layout);
        jpnMenu2Layout.setHorizontalGroup(
            jpnMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenu2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlbMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jpnMenu2Layout.setVerticalGroup(
            jpnMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenu2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlbMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jpnMenu3.setBackground(new java.awt.Color(0, 153, 153));

        jlbMenu3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbMenu3.setForeground(new java.awt.Color(255, 255, 255));
        jlbMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/thanh_toan.png"))); // NOI18N
        jlbMenu3.setText("Danh Sách Thanh Toán");
        jlbMenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jpnMenu3Layout = new javax.swing.GroupLayout(jpnMenu3);
        jpnMenu3.setLayout(jpnMenu3Layout);
        jpnMenu3Layout.setHorizontalGroup(
            jpnMenu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenu3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlbMenu3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jpnMenu3Layout.setVerticalGroup(
            jpnMenu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenu3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlbMenu3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jpnMenu4.setBackground(new java.awt.Color(0, 153, 153));

        jlbMenu4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbMenu4.setForeground(new java.awt.Color(255, 255, 255));
        jlbMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hoa_don.png"))); // NOI18N
        jlbMenu4.setText("Quản Lý Hoá Đơn");
        jlbMenu4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jpnMenu4Layout = new javax.swing.GroupLayout(jpnMenu4);
        jpnMenu4.setLayout(jpnMenu4Layout);
        jpnMenu4Layout.setHorizontalGroup(
            jpnMenu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenu4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlbMenu4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jpnMenu4Layout.setVerticalGroup(
            jpnMenu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnMenu4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlbMenu4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jpnMenu5.setBackground(new java.awt.Color(0, 153, 153));

        jlbMenu5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbMenu5.setForeground(new java.awt.Color(255, 255, 255));
        jlbMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/thong_ke.png"))); // NOI18N
        jlbMenu5.setText("Báo Cáo - Thống Kê");
        jlbMenu5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jpnMenu5Layout = new javax.swing.GroupLayout(jpnMenu5);
        jpnMenu5.setLayout(jpnMenu5Layout);
        jpnMenu5Layout.setHorizontalGroup(
            jpnMenu5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenu5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlbMenu5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jpnMenu5Layout.setVerticalGroup(
            jpnMenu5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenu5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlbMenu5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nhóm 15");

        javax.swing.GroupLayout jpnMenuLayout = new javax.swing.GroupLayout(jpnMenu);
        jpnMenu.setLayout(jpnMenuLayout);
        jpnMenuLayout.setHorizontalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnMenuTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpnMenu5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnMenu2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnMenu3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnMenu4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnMenuLayout.setVerticalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addComponent(jpnMenuTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jpnMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jpnMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jpnMenu3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jpnMenu4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jpnMenu5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(10, 10, 10))
        );

        jpnView.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 668, Short.MAX_VALUE)
        );

        jpnStatusBar.setBackground(new java.awt.Color(204, 204, 204));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jlbTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jlbDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jpnStatusBarLayout = new javax.swing.GroupLayout(jpnStatusBar);
        jpnStatusBar.setLayout(jpnStatusBarLayout);
        jpnStatusBarLayout.setHorizontalGroup(
            jpnStatusBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnStatusBarLayout.createSequentialGroup()
                .addComponent(jlbMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbDate, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbTime, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpnStatusBarLayout.setVerticalGroup(
            jpnStatusBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jlbTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jlbDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
            .addComponent(jSeparator2)
            .addComponent(jlbMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpnRootLayout = new javax.swing.GroupLayout(jpnRoot);
        jpnRoot.setLayout(jpnRootLayout);
        jpnRootLayout.setHorizontalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addComponent(jpnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jpnStatusBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnRootLayout.setVerticalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jpnStatusBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jlbDate;
    private javax.swing.JLabel jlbMenu1;
    private javax.swing.JLabel jlbMenu2;
    private javax.swing.JLabel jlbMenu3;
    private javax.swing.JLabel jlbMenu4;
    private javax.swing.JLabel jlbMenu5;
    private javax.swing.JLabel jlbMenuTitle;
    private javax.swing.JLabel jlbMessage;
    private javax.swing.JLabel jlbTime;
    private javax.swing.JPanel jpnMenu;
    private javax.swing.JPanel jpnMenu1;
    private javax.swing.JPanel jpnMenu2;
    private javax.swing.JPanel jpnMenu3;
    private javax.swing.JPanel jpnMenu4;
    private javax.swing.JPanel jpnMenu5;
    private javax.swing.JPanel jpnMenuTitle;
    private javax.swing.JPanel jpnRoot;
    private javax.swing.JPanel jpnStatusBar;
    private javax.swing.JPanel jpnView;
    // End of variables declaration//GEN-END:variables
}
