
package views;

import models.Thang;
import utility.JCustomTable;
import utility.JCustomTableBuilder;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;
import services.ThangServiceImpl;

/**
 *
 * @author Admin
 */
public class JDialog_ThemThang extends javax.swing.JDialog {

    /**
     * Creates new form JDialog_ThemThang
     */
    public JDialog_ThemThang() {
        super(main.Main.mainFrame, true);
        initComponents();
        initTable();
        initData();
        initEvent();
    }
    
    private JCustomTable jCustomTable_Thang;
    
    private final ThangServiceImpl thangServiceImpl = new ThangServiceImpl();
    private Thang thangInserted = new Thang();
    
    private void initEvent(){
        jButton_LuuThayDoi.addActionListener((ActionEvent e) -> {
            if (thangServiceImpl.createORUpdate(thangInserted) != 0){
                JOptionPane.showMessageDialog(null, "Thêm tháng thành công");
            }
            else{
                JOptionPane.showMessageDialog(null, "Có lỗi trong quá trình xử lý");
            }
            
            dispose();
        });
        
        jButton_TroVe.addActionListener((ActionEvent e) -> {
            dispose();
        });
    }
    
    private void initData(){
        Thang thangCuoiCung = thangServiceImpl.getLastThang();
        thangInserted.setThangID(thangCuoiCung.getThangID() + 1);
        
        Calendar calendar = Calendar.getInstance();
        
        calendar.setTime(thangCuoiCung.getNgayDau());
        calendar.add(Calendar.MONTH, 1);
        thangInserted.setNgayDau(calendar.getTime());
        
        calendar.setTime(thangCuoiCung.getNgayCuoi());
        calendar.add(Calendar.MONTH, 1);
        thangInserted.setNgayCuoi(calendar.getTime());
        
        jTextField_NgayDau.setText(Thang.dateToString(thangInserted.getNgayDau()));
        jTextField_NgayCuoi.setText(Thang.dateToString(thangInserted.getNgayCuoi()));
        jTextField_MaThang.setText(thangInserted.getThangID() + "");
    }
    
    private void initTable(){
        jCustomTable_Thang = new JCustomTableBuilder(jScrollPane_Thang)
                .addColumnName("Mã tháng")
                .addColumnName("Ngày đầu")
                .addColumnName("Ngày cuối")
                .build();
        
        jCustomTable_Thang.clear();
        
        List<List<Object>> obj = new ArrayList<>();
        List<Thang> list = thangServiceImpl.getList();
        list.forEach(thang -> { obj.add(thang.getAsList()); });
        
        jCustomTable_Thang.addRows(obj);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Root = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane_Thang = new javax.swing.JScrollPane();
        jButton_TroVe = new javax.swing.JButton();
        jButton_LuuThayDoi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField_MaThang = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_NgayDau = new javax.swing.JTextField();
        jTextField_NgayCuoi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách tháng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 15))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane_Thang)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane_Thang, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton_TroVe.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton_TroVe.setText("Trở về");

        jButton_LuuThayDoi.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton_LuuThayDoi.setText("Lưu thay đổi");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setText("Mã tháng");

        jTextField_MaThang.setEditable(false);
        jTextField_MaThang.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextField_MaThang.setText("Auto gen");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Ngày đầu");

        jTextField_NgayDau.setEditable(false);
        jTextField_NgayDau.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jTextField_NgayCuoi.setEditable(false);
        jTextField_NgayCuoi.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Ngày cuối");

        javax.swing.GroupLayout jPanel_RootLayout = new javax.swing.GroupLayout(jPanel_Root);
        jPanel_Root.setLayout(jPanel_RootLayout);
        jPanel_RootLayout.setHorizontalGroup(
            jPanel_RootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_RootLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_RootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_RootLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_RootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_RootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_MaThang, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(jTextField_NgayCuoi)
                            .addComponent(jTextField_NgayDau)))
                    .addGroup(jPanel_RootLayout.createSequentialGroup()
                        .addComponent(jButton_TroVe, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 417, Short.MAX_VALUE)
                        .addComponent(jButton_LuuThayDoi, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel_RootLayout.setVerticalGroup(
            jPanel_RootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_RootLayout.createSequentialGroup()
                .addGroup(jPanel_RootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_RootLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel_RootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField_MaThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel_RootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField_NgayDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_RootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField_NgayCuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_RootLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel_RootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_TroVe, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_LuuThayDoi, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Root, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Root, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_LuuThayDoi;
    private javax.swing.JButton jButton_TroVe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_Root;
    private javax.swing.JScrollPane jScrollPane_Thang;
    private javax.swing.JTextField jTextField_MaThang;
    private javax.swing.JTextField jTextField_NgayCuoi;
    private javax.swing.JTextField jTextField_NgayDau;
    // End of variables declaration//GEN-END:variables
}
